//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InboxWatcher
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailFilter
    {
        public int Id { get; set; }
        public string FilterName { get; set; }
        public string SubjectContains { get; set; }
        public string SentFromContains { get; set; }
        public string ForwardToAddress { get; set; }
        public bool ForwardThis { get; set; }
        public string MoveToFolder { get; set; }
    }
}
