//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InboxWatcher
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email : IEmail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Email()
        {
            this.EmailLogs = new HashSet<EmailLog>();
        }
    
        public int Id { get; set; }
        public bool InQueue { get; set; }
        public int Minutes { get; set; }
        public string Sender { get; set; }
        public System.DateTime TimeReceived { get; set; }
        public string Subject { get; set; }
        public bool MarkedAsRead { get; set; }
        public string BodyText { get; set; }
        public string EnvelopeID { get; set; }
        public int ImapMailBoxConfigurationId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailLog> EmailLogs { get; set; }
        public virtual ImapMailBoxConfiguration ImapMailBoxConfiguration { get; set; }
    }
}
