//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using InboxWatcher.Interface;

namespace InboxWatcher
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailLog : IEmailLog
    {
        public int Id { get; set; }
        public string TakenBy { get; set; }
        public string Action { get; set; }
        public System.DateTime TimeActionTaken { get; set; }
        public int EmailId { get; set; }
    
        public virtual Email Email { get; set; }
    }
}
