//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InboxWatcher
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MailModelContainer : DbContext
    {
        public MailModelContainer()
            : base("name=MailModelContainer")
        {
    	this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Email> Emails { get; set; }
        public virtual DbSet<EmailLog> EmailLogs { get; set; }
        public virtual DbSet<EmailFilter> EmailFilters { get; set; }
        public virtual DbSet<ImapMailBoxConfiguration> ImapMailBoxConfigurations { get; set; }
        public virtual DbSet<NotificationConfiguration> NotificationConfigurations { get; set; }
    }
}
