//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InboxWatcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InboxWatcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //     Backbone.js 1.2.3
        ///
        /////     (c) 2010-2015 Jeremy Ashkenas, DocumentCloud and Investigative Reporters &amp; Editors
        /////     Backbone may be freely distributed under the MIT license.
        /////     For all details and documentation:
        /////     http://backbonejs.org
        ///
        ///(function (factory) {
        ///
        ///    // Establish the root object, `window` (`self`) in the browser, or `global` on the server.
        ///    // We use `self` instead of `window` for `WebWorker` support.
        ///    var root = (typeof self == &apos;object&apos; &amp;&amp; self.self == self &amp;&amp;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string backbone {
            get {
                return ResourceManager.GetString("backbone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;/&gt;
        ///    &lt;title&gt;Configuration&lt;/title&gt;
        ///    &lt;script src=&quot;/js/jquery.js&quot;&gt;&lt;/script&gt;
        ///    &lt;script src=&quot;/js/underscore.js&quot;&gt;&lt;/script&gt;
        ///    &lt;script src=&quot;/js/backbone.js&quot;&gt;&lt;/script&gt;
        ///
        ///    &lt;!-- Latest compiled and minified CSS --&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css&quot; integrity=&quot;sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string configuration {
            get {
                return ResourceManager.GetString("configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;/&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///
        ///    &lt;title&gt;Inbox Watcher Dashboard&lt;/title&gt;
        ///
        ///    &lt;script src=&quot;/api/Jquery&quot;&gt;&lt;/script&gt;
        ///
        ///    &lt;!-- Latest compiled and minified CSS --&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css&quot; integrity=&quot;sha384-1q8mTJOA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * Base structure
        /// */
        ///
        ////* Move down content because we have a fixed navbar that is 50px tall */
        ///body {
        ///  padding-top: 50px;
        ///}
        ///
        ///
        ////*
        /// * Global add-ons
        /// */
        ///
        ///.sub-header {
        ///  padding-bottom: 10px;
        ///  border-bottom: 1px solid #eee;
        ///}
        ///
        ////*
        /// * Top navigation
        /// * Hide default border to remove 1px line.
        /// */
        ///.navbar-fixed-top {
        ///  border: 0;
        ///}
        ///
        ////*
        /// * Sidebar
        /// */
        ///
        ////* Hide for mobile, show later */
        ///.sidebar {
        ///  display: none;
        ///}
        ///@media (min-width: 768px) {
        ///  .sidebar {
        ///    position: fi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dashboard1 {
            get {
                return ResourceManager.GetString("dashboard1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Backbone.Epoxy 1.3.3
        ///// (c) 2015 Greg MacWilliam
        ///// Freely distributed under the MIT license
        ///// http://epoxyjs.org
        ///(function (t, e) { &quot;undefined&quot; != typeof exports ? module.exports = e(require(&quot;underscore&quot;), require(&quot;backbone&quot;)) : &quot;function&quot; == typeof define &amp;&amp; define.amd ? define([&quot;underscore&quot;, &quot;backbone&quot;], e) : e(t._, t.Backbone) })(this, function (t, e) { function n(t, e, n) { return t._super.prototype[e].apply(t, n) } function i(e, n, r, o) { for (var s in n) if (n.hasOwnProperty(s)) { var u = n[ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string epoxy {
            get {
                return ResourceManager.GetString("epoxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v2.1.4 | (c) 2005, 2015 jQuery Foundation, Inc. | jquery.org/license */
        ///!function(a,b){&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return b(a)}:b(a)}(&quot;undefined&quot;!=typeof window?window:this,function(a,b){var c=[],d=c.slice,e=c.concat,f=c.push,g=c.indexOf,h={},i=h.toString,j=h.hasOwnProperty,k={},l=a.document,m=&quot;2.1.4&quot;,n=function(a,b){return new n.fn.init(a,b)},o=/^[ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_2_1_4_min {
            get {
                return ResourceManager.GetString("jquery_2_1_4_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //     Underscore.js 1.8.3
        /////     http://underscorejs.org
        /////     (c) 2009-2015 Jeremy Ashkenas, DocumentCloud and Investigative Reporters &amp; Editors
        /////     Underscore may be freely distributed under the MIT license.
        ///
        ///(function () {
        ///
        ///    // Baseline setup
        ///    // --------------
        ///
        ///    // Establish the root object, `window` in the browser, or `exports` on the server.
        ///    var root = this;
        ///
        ///    // Save the previous value of the `_` variable.
        ///    var previousUnderscore = root._;
        ///
        ///    // Save bytes in [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string underscore {
            get {
                return ResourceManager.GetString("underscore", resourceCulture);
            }
        }
    }
}
